config/routes.rb
Rails.application.routes.draw do
  get '/top_page', to: 'sessions#index', as: 'top_page'
  resources :users
  resources :assignments
  
  # 帳票出力用の処理URL
  #post '/assignments/output', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/output_csv', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/index_output_excel/:id', to: 'assignments#output_index', as: 'index_output_excel'
  get '/teaching_assistants/index_destroy', to: 'teaching_assistants#index_destroy', as: 'index_destroy_teaching_assistants'
  delete '/teaching_assistants/index_destroy', to: 'teaching_assistants#destroy'
  resources :teaching_assistants do
    collection {post :import}
  end
  
  get '/courses/index_destroy', to: 'courses#index_destroy', as: 'index_destroy_courses'
  delete '/courses/index_destroy', to: 'courses#destroy'
  delete '/courses/:course_id/assignments/:assignment_id/work_hours/:id', to: 'assignments#destroy', as: 'destroy_course_assignments'
  get '/courses/:course_id/assignments/index_destroy', to: 'assignments#index_destroy', as: 'index_destroy_course_assignments'
  delete '/courses/:course_id/assignments/index_destroy', to: 'assignments#TAdestroy'
  resources :courses do
    resources :assignments
    collection {post :import}
  end
  
  #resources :work_hours  
  resources :courses do
    resources :work_hours  
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # セッション管理
  get "/login",  to: "sessions#new"
  post "/login",  to: "sessions#create"
  get "/admin_login",  to: "sessions#admin_new"
  post "/admin_login",  to: "sessions#admin_create"
  delete "/logout",  to: "sessions#destroy"

  get "/sessions/admin_new",  to: "sessions#admin_new"

  # Defines the root path route ("/")
   root "sessions#new"
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :course
  belongs_to :teaching_assistant
  has_many :work_hours, dependent: :destroy

  validates :description,
  length: {maximum: 128}

  def self.ransackable_attributes(auth_object = nil)
    ["course_id", "created_at", "description", "id", "teaching_assistant_id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["course","teaching_assistant", "work_hours"]
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  before_action :login, only: %i[index show new create edit update destroy output_index]

  # 使用中
  # GET /assignments or /assignments.json
  def index
    @course = Course.find(params[:course_id])
    @q = @course.assignments.ransack(params[:q], course_id_eq: @course.id)
    @q.sorts = "work_hours_dtstart ASC" if @q.sorts.empty?
    @assignments = @q.result(distinct: true)
    @sum_actual_working_minutes = @assignments.map { |assignment| assignment.work_hours.sum(:actual_working_minutes) }.sum
  end

  # GET /assignments/1 or /assignments/1.json
  def show
    # ============#
    # 使用してない =#
    # ============#
  end

  # GET /assignments/new
  def new
    @course = Course.find(params[:course_id])
    @assignment = Assignment.new
    @q = TeachingAssistant.ransack(params[:q])
    @teaching_assistants = @q.result(distinct: true)
    @select_years = TeachingAssistant.where.not(id: 1).pluck(:year).uniq
  end

  # GET /assignments/1/edit
  def edit
    # ============#
    # 使用してない =#
    # ============#
    # @course = Course.find(params[course_id:])
    # @assignment = @course.assignments.find(params[assignment_id:])
    # @work_hour = @assignment.work_hours.find(params[id:])
  end  

  # POST /assignments or /assignments.json
  def create
    @course = Course.find(params[:course_id]) 
    if params[:teaching_assistant_ids].nil?
      redirect_to new_course_assignment_path(@course), notice: "追加したいTA候補を選択してください", flash: {color: :red}
    else  
      @teaching_assistants = TeachingAssistant.where(id: params[:teaching_assistant_ids])
      @teaching_assistants.each do |teaching_assistant|
        @assignment = Assignment.new({course_id:@course.id,teaching_assistant_id:teaching_assistant.id, description:""})      
        if Assignment.where(course_id: @course.id).where(teaching_assistant_id: teaching_assistant.id).count >= 1
          #データが重複しないようにif文ではじく
          next
        else
          @assignment.save
        end
      end
      redirect_to course_assignments_path(@course), notice: "TA候補が追加されました．", flash: {color: :green}
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignment_url(@assignment), notice: "Assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  def index_destroy
    @course = Course.find(params[:course_id])
    @q = TeachingAssistant.ransack(params[:q])
    @teaching_assistants = @q.result(distinct: true).joins(:assignments).where(assignments: {course_id: @course.id})
    @select_years = TeachingAssistant.joins(:assignments).where.not(id: 1).where(assignments: { course_id: @course.id }).pluck(:year).uniq
    @select_years.insert(0,"")
  end
  

  def TAdestroy
    if params[:teaching_assistant_ids].nil?
      redirect_to index_destroy_course_assignments_path, notice: "削除したいTA候補を選択してください", flash: {color: :red}
    else
      @assignments = Assignment.where(teaching_assistant_id: params[:teaching_assistant_ids])
      @assignments.destroy_all
      redirect_to index_destroy_course_assignments_path, notice: "TA候補が削除されました", flash: {color: :green}
    end
  end

  # (非同期時の調べ物)割当の削除ボタンを押すとこの処理に来る
  def destroy
    @assignment = Assignment.find(params[:assignment_id])
    @work_hour = @assignment.work_hours.find(params[:id])
    @work_hour.destroy

    respond_to do |format|
      # format.turbo_stream
      format.html { redirect_to course_assignments_path, notice: "Work hour was successfully destroyed." }
      format.json { head :no_content }
      # redirect_to course_assignments_path, notice: "割当時間が削除されました", flash: {color: :green}
      format.turbo_stream
    end
  end

  def output_index
    if params[:id].to_i == 1
      render plain: "アクセスが制限されています", status: :forbidden
    else
      @teaching_assistant = TeachingAssistant.find(params[:id])
      @assignments = Assignment.where(teaching_assistant_id: params[:id])
      date_start = Date.new(@teaching_assistant.year, 4, 1) 
      date_end = Date.new(@teaching_assistant.year+1, 3, 31) 
      count = WriteForm1(date_start, date_end)
      WriteForm2(date_start, date_end)

      @output_excel1_files_name = [];
      for i in 1..count do
        @output_excel1_files_name.push("/excel/writed_form1-#{i}.xlsx")
      end
      @output_excel2_file_name = "/excel/writed_form2.xlsx"
    end
  end

  def output
    @teaching_assistant = TeachingAssistant.find(params[:teaching_assistant_id])
    date_start = Date.new(@teaching_assistant.year, 4, 1) 
    date_end = Date.new(@teaching_assistant.year+1, 4, 1) 

    if params[:form] == '1'
      WriteForm1(date_start, date_end)
      file_path = Rails.root.join('public', 'excel','writed_form1-1.xlsx')
      send_file file_path, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', disposition: 'attachment'
    else
      WriteForm2(date_start, date_end)
      file_path = Rails.root.join('public', 'excel','writed_form2.xlsx')
      send_file file_path, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', disposition: 'attachment'
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:course_id, :teaching_assistant_id, :description)
    end

    # 帳票の様式1を書き込む処理を行うメソッド
    def WriteForm1(date_start, date_end)
      # 書き込むファイル名 勤務予定が15個ごと書き込んだエクセルファイルを作成するので，ファイル名を変えたい．保存ファイル名の変えない部分
      first = "public/excel/writed_form1"
      # ファイル名を変更するためのマジックナンバー
      file_change_count = 1

      # 様式1のエクセルファイルを読み込む
      file_form1 = "public/excel/form1.xlsx"
      # エクセルを読み込む処理
      workbook_form1 = RubyXL::Parser.parse(file_form1)
      # エクセルの書き込みを行うシートを指定「0からスタートする」
      worksheet_form1 = workbook_form1[1]

      # 書き込みを行いたいTAが持っている割当をDBから持ってくる
      @assignments = Assignment.where(teaching_assistant_id: @teaching_assistant.id)
      # 今書き込んでいる割当の数-1
      count = 0;
      # 合計勤務時間
      sum_work_time = 0
      # 曜日を変換するための配列
      days = ["日", "月", "火", "水", "木", "金", "土"]

      # 氏名追加処理
      worksheet_form1.add_cell(9, 20, @teaching_assistant.labo[0...-1])
      (20..28).each do |col|
        cell = worksheet_form1[9][col]
        next if cell.nil?
        cell.change_border(:bottom, "thin")
      end
      worksheet_form1.add_cell(18, 2, @teaching_assistant.name)
      (2..12).each do |col|
        cell = worksheet_form1[18][col]
        next if cell.nil?
        cell.change_border(:bottom, "thin")
      end

      # 学生番号追加処理
      worksheet_form1.add_cell(18, 21, @teaching_assistant.number)

      # 所属分岐　学年ごとに分岐されている
      if @teaching_assistant.grade == "M1" or @teaching_assistant.grade == "M2" then
        worksheet_form1.add_cell(20, 15, @teaching_assistant.grade[-1])
        worksheet_form1.add_cell(19, 2, "大学院環境生命自然科学研究科")
        worksheet_form1.add_cell(19, 15, "前")
      elsif @teaching_assistant.grade == "D1" or @teaching_assistant.grade == "D2" or @teaching_assistant.grade == "D3" then
        worksheet_form1.add_cell(20, 15, @teaching_assistant.grade[-1])
        worksheet_form1.add_cell(19, 2, "大学院環境生命自然科学研究科")
        worksheet_form1.add_cell(19, 15, "後")
      else
        worksheet_form1.add_cell(22, 14, @teaching_assistant.grade)
      end

      # 割り当てられた講義
      @assignments.each do |assignment|
        @work_hours = WorkHour.where(assignment_id: assignment.id).where(dtstart: date_start..).where(dtend: ..date_end).order(:dtstart)
        @course = Course.where(id: assignment.course_id)
        @work_hours.each do |work_hour|
          worksheet_form1.add_cell(36+count, 1, @course.first.number)
          worksheet_form1.add_cell(36+count, 3, @course.first.name)
          worksheet_form1.add_cell(36+count, 8, @course.first.term)
          worksheet_form1.add_cell(36+count, 9, days[work_hour.dtstart.wday])
          worksheet_form1.add_cell(36+count, 11, work_hour.dtstart.strftime('%Y-%m-%d %H:%M') )
          worksheet_form1.add_cell(36+count, 16, work_hour.dtend.strftime('%Y-%m-%d %H:%M') )
          worksheet_form1.add_cell(36+count, 20, work_hour.actual_working_minutes )
          sum_work_time = sum_work_time + work_hour.actual_working_minutes
          (1..35).each do |col|
            cell = worksheet_form1[36+count][col]
            next if cell.nil?
            cell.change_border(:top, "thin")
            cell.change_border(:left, "thin")
            cell.change_border(:right, "thin")
            cell.change_border(:bottom, "thin")
          end
          count += 1

          if count == 15 then
            # とりあえず今まで作成したものを保存する
            workbook_form1.write("#{first}-#{file_change_count}.xlsx")
            # workbook_form1.write("#{first}.xlsx")
            file_change_count +=1
            file_form1 = "public/excel/form1.xlsx"
            count = 0

            workbook_form1 = RubyXL::Parser.parse(file_form1)
            worksheet_form1 = workbook_form1[1]

            # 氏名追加処理
            worksheet_form1.add_cell(9, 20, @teaching_assistant.labo[0...-1])
            (20..28).each do |col|
              cell = worksheet_form1[9][col]
              next if cell.nil?
              cell.change_border(:bottom, "thin")
            end
            worksheet_form1.add_cell(18, 2, @teaching_assistant.name)
            (2..12).each do |col|
              cell = worksheet_form1[18][col]
              next if cell.nil?
              cell.change_border(:bottom, "thin")
            end

            # 学生番号追加処理
            worksheet_form1.add_cell(18, 21, @teaching_assistant.number)

            # 所属分岐
            if @teaching_assistant.grade == "M1" or @teaching_assistant.grade == "M2" then

app/helpers/assignments_helper.rb
module AssignmentsHelper
	def sort
		work_hours = WorkHour.where(assignment_id: Assignment.where(teaching_assistant_id: @teaching_assistant.id))
		.where(dtstart: Date.new(@teaching_assistant.year,4,1)..)
		.where(dtend: ..Date.new(@teaching_assistant.year+1,4,1))
		.select("strftime('%Y年%m月%d日', dtstart) AS month_day, sum(actual_working_minutes) AS sum_work_time").group("month_day")
	end

	def all_work_time
		work_hours = WorkHour.where(assignment_id: Assignment.where(teaching_assistant_id: @teaching_assistant.id))
		.where(dtstart: Date.new(@teaching_assistant.year,4,1)..)
		.where(dtend: ..Date.new(@teaching_assistant.year+1,4,1))
		.sum(:actual_working_minutes)
	end

	def assigment_course_teacher
		teachers_name = []
		assignments = Assignment.where(teaching_assistant_id: @teaching_assistant.id)

		assignments.each do |assignment| 
			teachers_name.push(Course.where(id: assignment.course_id).first.instructor)
		end

		return teachers_name
	end

	def datetoday(work_hour)
		days = ["日", "月", "火", "水", "木", "金", "土"]

		return days[work_hour.dtstart.wday]
	end

	def datetoymdhm(date)
		return Date.new(date)
	end
end

app/views/assignments/_assignment_view.html.erb
<%# TA割当画面の表を表示している部分 %>
<%= turbo_frame_tag work_hour do %>
  <div class="row py-2 border-top">
    <div class="col my-auto"><%= work_hour.date %></div>
    <div class="col my-auto"><%= work_hour.dtstart.strftime("%H:%M") %></div>
    <div class="col my-auto"><%= work_hour.dtend.strftime("%H:%M") %></div>
    <div class="col my-auto"><%= work_hour.actual_working_minutes %></div>
    <div class="col my-auto">
      <% if assignment.teaching_assistant.id == 1 %>
        <%= "未登録" %>
      <% else %>
        <%= assignment.teaching_assistant.name %>
      <% end %>
    </div>
    <div class="col my-auto" style="display:flex; align-items: center; justify-content:center;">
      <div class="row">
        <div class="col-md-12 col-lg-6 my-1"><%= link_to "編集", edit_course_work_hour_path(course_id: assignment.course_id, id: work_hour.id), method: :get, class: 'btn btn-primary w-auto' %></div>
        <div class="col-md-12 col-lg-6 my-1"><%= button_to "削除", destroy_course_assignments_path(@course, assignment, work_hour), method: :delete, class: 'btn btn-danger w-auto', id:'delete-buttom', form: { data: { turbo_confirm: "本当に削除しますか？" } } %></div>
        <div class="col-md-12 col-lg-6 my-1">
          <% if assignment.teaching_assistant.id != 1 %>
            <%= link_to "個人画面", teaching_assistant_path(assignment.teaching_assistant),class: 'btn btn-success w-auto no_return', target: '_blank'%>
            <%#= link_to "個人<br>画面".html_safe, teaching_assistant_path(assignment.teaching_assistant),class: 'btn btn-success w-auto no_return', target: '_blank'%>
          <% end %>
        </div>
        <div class="col-md-12 col-lg-6 my-1">
          <% if assignment.teaching_assistant.id != 1 %>
            <%= link_to "帳票出力", index_output_excel_path(@teaching_assistant = assignment.teaching_assistant), target: :_blank, rel: "noopener noreferrer"  ,class: 'btn btn-secondary w-auto no_return' %>
            <%#= link_to "帳票<br>出力".html_safe, index_output_excel_path(@teaching_assistant = assignment.teaching_assistant), target: :_blank, rel: "noopener noreferrer"  ,class: 'btn btn-secondary w-auto no_return' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<style>
.no_return {
    white-space: nowrap;
}
</style>

app/views/assignments/create.turbo_stream.erb
<%# `#cats`の先頭に登録されたcatを追加する %>
<%#= turbo_stream.prepend "work_hour", @work_hour %>

<%# 登録の入力フォームの中身を空にする %>
<%#%= turbo_stream.update WorkHour.new, "" %>

<%# Flashを表示 %>
<%#= turbo_stream_flash %>
<%= turbo_frame_tag.prepend "assignments" work_hour do %>
	<div class="row py-2 border-top">
		<div class="col my-auto"><%= work_hour.dtstart %></div>
		<div class="col my-auto"><%= work_hour.dtend %></div>
		<div class="col my-auto"><%= work_hour.actual_working_minutes %></div>
		<div class="col my-auto"><%= assignment.teaching_assistant.name %></div>
		<div class="col my-auto">
			<%#= link_to "編集", edit_assignment_path(assignment, work_hour, course_id: assignment.course_id, assignment_id: assignment.id), method: :get, class: 'btn btn-danger', form: { style: 'display: inline' } %>
			<%= link_to "編集", edit_course_work_hour_path(course_id: assignment.course_id, id: work_hour.id), method: :get, class: 'btn btn-primary', form: { style: 'display: inline' } %>
			<%= button_to "削除", destroy_course_assignments_path(@course, assignment, work_hour), method: :delete, class: 'btn btn-danger', form: { style: 'display: inline' }, id:'delete-buttom', form: { data: { turbo_confirm: "本当に削除しますか？" } } %>
		</div>
	</div>
<% end %>
<%#= turbo_stream.prepend "assignments", @work_hour %>
<%= turbo_stream.update "new_work_hour", "" %>
<%#= turbo_stream_flash %>

app/views/assignments/index.html.erb
<%# TA時間割当画面(編集)を表示 %>
<div class="row">
  <div class="col-lg-1 col-md-0"></div>
  <%# TA勤務割当画面(編集)を表示 %>
  <div class="col-lg-10 col-md-12">
    <% if flash[:color] == "red" %>
      <div class="red-text"><%= flash[:notice] %></div>
    <% elsif flash[:color] == "green" %>
      <div class="green-text"><%= flash[:notice] %></div>
    <% else %>
      <div><%= flash[:notice] %></div>
    <% end %>

    <%# TAタイトルとマスタデータ関連 %>
    <div class="row">
      <div class="col-lg-4 col-md-12"><h2>TA勤務割当(編集)</h2></div>
      <div class="col-lg-6 col-md-0"></div>
      <div class="col-lg-2 col-md-12"><%= link_to "科目一覧に戻る", courses_path, class: "btn btn-outline-danger py-2" %></div>
    </div>

    <div class="row m-3">
      <div class="col-3 d-flex align-items-center"><h3 class="">科目：<%= @course.name %></h3></div>
      <div class="col-2 d-flex align-items-center">担当教員: <%= @course.instructor %></div>
      <div class="col-2 d-flex align-items-center">対象年度: <%= @course.year %></div>
      <div class="col-2 d-flex align-items-center">開講学期: <%= @course.term %></div>
      <div class="col-3 d-flex align-items-center">割当可能残時間(分): <%= @course.time_budget - @sum_actual_working_minutes %></div>
    </div>


    <%# 検索欄 %>
    <div class="card my-3">
      <div class="card-header">
        検索欄
      </div>
      <div class="card-body">
        <form class="row g-3">
          <%= search_form_for @q, html: {class:"row g-3"} do |f| %>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%=f.label :teaching_assistant_name_i_cont, "TA名", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :teaching_assistant_name_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-12 text-center mt-5">
              <%= f.submit "検索", class: "ms-5 btn btn-primary px-4"%>
              <%= link_to "クリア", course_assignments_path(@course), class: "ms-5 btn btn-danger px-4" %>
            </div>
          <% end %>
        </form>
      </div>
    </div>

    <%# TA勤務割当処理 %>
    <div class="card my-3">
      <div class="card-header">
        <%#= icon_with_text("table", "一覧") %>
        <div class="row">
          <div class="col-3 d-flex align-items-center">TA勤務割当処理</div>
          <div class="col-2"><%= link_to "勤務追加", new_course_work_hour_path, class: "btn btn-outline-success", data: { turbo_frame: "new_work_hour" }  %></div>
          <div class="col-2"><%= link_to "TA候補追加", new_course_assignment_path, class: "btn btn-outline-primary", method: :get %></div>
          <div class="col-2"><%= link_to "TA候補削除", index_destroy_course_assignments_path, class: "btn btn-outline-danger", method: :delete %></div>
          <div></div class="col-3">
        </div>
      </div>
      <div class="card-body mx-3">
        <div class="row py-2">
          <div class="col my-auto">日付</div>
          <div class="col my-auto">開始時刻</div>
          <div class="col my-auto">終了時刻</div>
          <div class="col my-auto">実働時間(分)</div>
          <div class="col my-auto">割当TA名</div>
          <div class="col my-auto">操作</div>
        </div>
        <%= turbo_frame_tag "new_work_hour" %>
        <div id="assignments">
        <% @assignments.each do |assignment| %>
          <% assignment.work_hours.each do|work_hour| %>
            <%= render partial: 'assignment_view', locals:{ assignment: assignment,work_hour: work_hour } %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>

app/views/assignments/index_destroy.html.erb
<%# TA候補削除画面を表示する． %>
<div class="row">
  <div class="col-lg-1 col-md-0"></div>
  <%# TA候補削除画面の処理部分 %>
  <div class="col-lg-10 col-md-12">
    <%# メッセージ処理部分 %>
    <% if flash[:color] == "red" %>
      <div class="red-text"><%= flash[:notice] %></div>
    <% elsif flash[:color] == "green" %>
      <div class="green-text"><%= flash[:notice] %></div>
    <% else %>
      <div><%= flash[:notice] %></div>
    <% end %>

    <%# TA候補削除画面 %>
    <div class="row ">
      <div class="col-lg-4 col-md-12"><h2>TA候補削除</h2></div>
      <div class="col-lg-6 col-md-0"></div>
      <div class="col-lg-2 col-md-12 d-flex align-items-center "><%= link_to "TA勤務割当(編集)に戻る", course_assignments_path, class: "btn btn-outline-danger py-2" %></div>
    </div>

    <%# 検索欄 %>
    <div class="card my-3">
      <div class="card-header">
        検索欄
      </div>
      <div class="card-body">
        <form class="row g-3">
          <%= search_form_for @q, html: {class:"row g-3"} do |f| %>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :year_eq, "対象年度",class: "mt-2" %></div>
                <div class="col-8"><%= f.select :year_eq, @select_years, {prompt:"対象年度を選択"},class: "form-control" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :name_i_cont, "TA名",class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :name_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>  
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :number_i_cont, "学生番号", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :number_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "8" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :grade_i_cont, "学年", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :grade_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "2" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :labo_i_cont, "研究室", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :labo_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :description_i_cont, "備考", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :description_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-12 text-center mt-5">
              <%= f.submit "検索", class: "ms-5 btn btn-primary px-4"%>
              <%= link_to "クリア", teaching_assistants_path, class: "ms-5 btn btn-danger px-4" %>
            </div>
          <% end %>
        </form>
      </div>
    </div>

  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>


<%# TA候補追加表 %>
<%= form_tag index_destroy_course_assignments_path(@course), method: :delete, data: {turbo_confirm: "選択したTAを削除した場合、選択したTAの割り当て時間も消えてしまいますが、本当に削除しますか?"} do %>
<div class="row mb-3">
  <div class="col-lg-1 col-md-0"></div>
  <%# TA候補追加表 %>
  <div class="col-lg-10 col-md-12">
    <div class="card">
      <div class="card-header">
          <div class="row">
            <div class="col-3 d-flex align-items-center">TA候補削除</div>
            <div class="col-9"><%= submit_tag '選択したTAをすべて候補から削除', class: "ms-5 btn btn-danger px-3" %></div>
          </div>
      </div>
      <div class="card-body m-3">
        <%# TA候補追加のカラムのヘッダー %>
        <div class="row border-bottom border-dark pb-3">
          <div class="col my-auto fw-bolder h5">TA候補者選択</div>
          <div class="col my-auto fw-bolder h5">対象年度</div>
          <div class="col my-auto fw-bolder h5">TA名</div>
          <div class="col my-auto fw-bolder h5">学生番号</div>
          <div class="col my-auto fw-bolder h5">学年</div>
          <div class="col my-auto fw-bolder h5">研究室</div>
          <div class="col my-auto fw-bolder h5">備考</div>
        </div>
        <%# TAのレコードデータ %>
        <div id="teaching_assistants">
          <% @teaching_assistants.each do |teaching_assistant| %>
            <div class="row border-bottom px-3 py-2">
              <% if teaching_assistant.id == 1 %>
                <% next %>
              <% else %>
                <div class="col my-auto"><%= check_box_tag 'teaching_assistant_ids[]', teaching_assistant.id %></div>
                <div class="col my-auto"><%= teaching_assistant.year %></div>
                <div class="col my-auto"><%= teaching_assistant.name %></div>
                <div class="col my-auto"><%= teaching_assistant.number %></div>
                <div class="col my-auto"><%= teaching_assistant.grade %></div>
                <div class="col my-auto"><%= teaching_assistant.labo %></div>
                <div class="col my-auto"><%= teaching_assistant.description %></div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>
<% end %>