config/routes.rb
Rails.application.routes.draw do
  get '/top_page', to: 'sessions#index', as: 'top_page'
  resources :users
  resources :assignments
  
  # 帳票出力用の処理URL
  #post '/assignments/output', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/output_csv', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/index_output_excel/:id', to: 'assignments#output_index', as: 'index_output_excel'
  get '/teaching_assistants/index_destroy', to: 'teaching_assistants#index_destroy', as: 'index_destroy_teaching_assistants'
  delete '/teaching_assistants/index_destroy', to: 'teaching_assistants#destroy'
  resources :teaching_assistants do
    collection {post :import}
  end
  
  get '/courses/index_destroy', to: 'courses#index_destroy', as: 'index_destroy_courses'
  delete '/courses/index_destroy', to: 'courses#destroy'
  delete '/courses/:course_id/assignments/:assignment_id/work_hours/:id', to: 'assignments#destroy', as: 'destroy_course_assignments'
  get '/courses/:course_id/assignments/index_destroy', to: 'assignments#index_destroy', as: 'index_destroy_course_assignments'
  delete '/courses/:course_id/assignments/index_destroy', to: 'assignments#TAdestroy'
  resources :courses do
    resources :assignments
    collection {post :import}
  end
  
  #resources :work_hours  
  resources :courses do
    resources :work_hours  
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # セッション管理
  get "/login",  to: "sessions#new"
  post "/login",  to: "sessions#create"
  get "/admin_login",  to: "sessions#admin_new"
  post "/admin_login",  to: "sessions#admin_create"
  delete "/logout",  to: "sessions#destroy"

  get "/sessions/admin_new",  to: "sessions#admin_new"

  # Defines the root path route ("/")
   root "sessions#new"
end

app/models/work_hour.rb
class WorkHour < ApplicationRecord
  belongs_to :assignment
  has_one :teaching_assistant, through: :assignment
  has_one :course, through: :assignment
  validates :date, presence: true
  validates :dtstart, presence: true
  validates :dtend, comparison: {greater_than: :dtstart, message: "%{attribute}は開始時刻よりも後にして下さい"}, presence: true
  validates :actual_working_minutes, numericality: {in: 1..10000, message: "%{attribute}は1以上10000以下で入力してください"}, presence: true
  validate :no_overlap_with_existing_times, unless: -> { teaching_assistant.id == 1 }
  before_create :check_actual_working_minutes

  def date=(date)
    @date = date
  end

  def date
    @date || dtstart.try(:to_date)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["actual_working_minutes", "assignment_id", "created_at", "dtend", "dtstart", "id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["assignment"]
  end

  def no_overlap_with_existing_times
    existing_times = teaching_assistant.work_hours.where.not(id: id)

    existing_times.each do |existing_time|
      if overlap?(existing_time)
        errors.add(:base, "既存の勤務時間と重なっています")
        break
      end
    end
  end

  def check_actual_working_minutes
    time_budget = assignment.course.time_budget

    total_actual_working_minutes = assignment.course.work_hours.sum(:actual_working_minutes)

    total_actual_working_minutes += self.actual_working_minutes

    if total_actual_working_minutes > time_budget
      errors.add(:actual_working_minutes, "合計勤務時間が割当可能総時間を超えています")
      throw :abort
    end
  end

  private

  def overlap?(other_time)
    dtstart < other_time.dtend && other_time.dtstart < dtend
  end
end

app/controllers/work_hours_controller.rb
class WorkHoursController < ApplicationController
  before_action :login, only: %i[ index show new edit create update destroy]
  before_action :set_work_hour, only: %i[ show edit update destroy ]

  # GET /work_hours or /work_hours.json
  def index
    @work_hours = WorkHour.all
  end

  # GET /work_hours/1 or /work_hours/1.json
  def show
  end

  # GET /work_hours/new
  def new
    @course = Course.find(params[:course_id])
    @work_hour = WorkHour.new
    @assignments = @course.assignments.includes(:teaching_assistant)
  end  

  # GET /work_hours/1/edit
  def edit
    @course = Course.find(params[:course_id])
    @work_hour = WorkHour.find(params[:id])
    @assignments = @course.assignments.includes(:teaching_assistant)
  end
  

  # POST /work_hours or /work_hours.json
  def create
    @course = Course.find(params[:course_id])

    date = params[:work_hour][:date]
    dtstart = params[:work_hour][:dtstart]
    dtend = params[:work_hour][:dtend]
  
    @work_hour = WorkHour.new(
      date: date,
      dtstart: "#{date}-#{dtstart}", 
      dtend: "#{date}-#{dtend}",    
      actual_working_minutes: params[:work_hour][:actual_working_minutes],
      assignment_id: params[:work_hour][:assignment_id]
    )
    @assignments = @course.assignments.includes(:teaching_assistant)


    if @work_hour.assignment_id.blank?
      @work_hour.assignment_id = @course.assignments.find { |a| a.teaching_assistant_id == 1 }&.id
    end
  
    respond_to do |format|
      if @work_hour.save
        format.html { redirect_to course_assignments_path, notice: "Work hour was successfully created." }
        format.json { render :show, status: :created, location: @work_hour }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_hour.errors, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@work_hour, partial: "form", locals: { work_hour: @work_hour }), status: :unprocessable_entity }
      end
    end    
  end



  # PATCH/PUT /work_hours/1 or /work_hours/1.json
  def update
    @course = Course.find(params[:course_id])
    @assignments = @course.assignments.includes(:teaching_assistant)

    if work_hour_params[:assignment_id].blank?
      assignment_id = @course.assignments.find { |a| a.teaching_assistant_id == 1 }&.id
    else
      assignment_id = work_hour_params[:assignment_id]
    end
    
    respond_to do |format|
    if @work_hour.update(work_hour_params.merge(assignment_id: assignment_id))
        #format.html { redirect_to work_hour_url(@work_hour), notice: "Work hour was successfully updated." }
        format.html { redirect_to course_assignments_path, notice: "Work hour was successfully updated." }
        format.json { render :show, status: :ok, location: @work_hour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_hours/1 or /work_hours/1.json
  def destroy
    @work_hour.destroy

    respond_to do |format|
      format.html { redirect_to work_hours_url, notice: "Work hour was successfully destroyed." }
      format.json { head :no_content }
      # 非同期で入れ替えるコードを記入[destroy.turbo_frame.erb]
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_hour
      @work_hour = WorkHour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_hour_params
      params.require(:work_hour).permit(:date, :dtstart, :dtend, :actual_working_minutes, :assignment_id)
    end
end

app/helpers/work_hours_helper.rb
module WorkHoursHelper
end

app/views/work_hours/_form.html.erb
<%# 非同期で編集モード時に表示変更するコード %>
<%= turbo_frame_tag work_hour do %>
  <%= bootstrap_form_with(model: [@course, @work_hour]) do |form| %>
      <% if work_hour.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(work_hour.errors.count, "error") %> prohibited this work_hour from being saved:</h2>

          <ul>
            <% work_hour.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="row py-2 border-top">
      <div class="col">  
        <% if work_hour.date %>
          <%= form.date_field :date, value: work_hour.date.to_date.strftime("%Y-%m-%d") %>
        <% else %>
          <%= form.date_field :date %>
        <% end %>
      </div>

      <div class="col">
        <% if work_hour.dtstart %>
          <%= form.time_field :dtstart, value: work_hour.dtstart.strftime("%H:%M") %>
        <% else %>
          <%= form.time_field :dtstart %>
        <% end %>
      </div>

      <div class="col">
        <% if work_hour.dtend %>
          <%= form.time_field :dtend, value: work_hour.dtend.strftime("%H:%M") %>
        <% else %>
          <%= form.time_field :dtend %>
        <% end %>  
      </div>

      <div class="col">
        <%#= form.label :actual_working_minutes, style: "display: block" %>
        <%= form.number_field :actual_working_minutes %>
      </div>

      <div class="col">
        <%#= form.label :assignment_id, style: "display: block" %>
        <%#= form.select :assignment_id, @assignments.map { |a| ["#{a.teaching_assistant.name} - #{a.teaching_assistant.number}", a.id] }, prompt: 'Select Assignment' %>
        <%#= form.select :assignment_id, @assignments.reject { |a| a.teaching_assistant_id == 1 }.map { |a| ["#{a.teaching_assistant.name} - #{a.teaching_assistant.number}", a.id] }, prompt: 'Select Assignment' %>
        <%= form.select :assignment_id, @assignments.reject { |a| a.teaching_assistant_id == 1 }.map { |a| ["#{a.teaching_assistant.name} - #{a.teaching_assistant.number}", a.id] }, include_blank: '未登録' %>

      </div>

      <div class="col" style="display:flex; align-items: center; justify-content:center;">
        <div class="row">
          <div class="col-lg-6 col-md-12" ><%= form.submit "登録", class:"btn btn-secondary" %></div>
          <div class="col-lg-6 col-md-12"><%= link_to "戻る", course_assignments_path, class:"btn btn-warning" %></div>
        </div>
        <%#= link_to "Back", @work_hour, class: "btn btn-sm btn-outline-secondary" %>
      </div>

    </div>
  <% end %>
<% end %>

app/views/work_hours/_work_hour.html.erb
<%# 非同期処理でTA勤務割当で新規追加後に登録したときに表示される登録後のレコードの表示を入れ替える部分のコード %>
<%= turbo_frame_tag work_hour do %>
  <div class="row py-2 border-top">
    <div class="col my-auto"><%= work_hour.date %></div>
    <div class="col my-auto"><%= work_hour.dtstart.strftime("%H:%M") %></div>
    <div class="col my-auto"><%= work_hour.dtend.strftime("%H:%M") %></div>
    <div class="col my-auto"><%= work_hour.actual_working_minutes %></div>
    <div class="col my-auto">
      <% if TeachingAssistant.where(id:Assignment.where(id: work_hour.assignment_id).first.teaching_assistant_id).first.name == "ダミー君" %>
        <%= "未登録" %>
      <% else %>
        <%= TeachingAssistant.where(id:Assignment.where(id: work_hour.assignment_id).first.teaching_assistant_id).first.name %>
      <% end %>
    </div>
    <div class="col my-auto" style="display:flex; align-items: center; justify-content:center;">
      <div class="row">
        <div class="col-md-12 col-lg-6 my-1"><%= link_to "編集", edit_course_work_hour_path(course_id: Assignment.where(id: work_hour.assignment_id).first.course_id, id: work_hour.id), method: :get, class: 'btn btn-primary w-auto', form: { style: 'display: inline' } %></div>
        <div class="col-md-12 col-lg-6 my-1"><%= button_to "削除", destroy_course_assignments_path( @course=Course.where(id:Assignment.where(id: work_hour.assignment_id).first.course_id).first , assignment=Assignment.where(id: work_hour.assignment_id).first, work_hour), method: :delete, class: 'btn btn-danger w-auto', form: { style: 'display: inline' }, id:'delete-buttom', form: { data: { turbo_confirm: "本当に削除しますか？" } } %></div>
        <div class="col-md-12 col-lg-6 my-1">
          <% if assignment.teaching_assistant.id != 1 %>
            <%= link_to "個人画面", teaching_assistant_path(assignment.teaching_assistant),class: 'btn btn-success w-auto no_return', target: '_blank'%>
            <%#= link_to "個人<br>画面".html_safe, teaching_assistant_path(assignment.teaching_assistant),class: 'btn btn-success w-auto no_return', target: '_blank'%>
          <% end %>
        </div>
        <div class="col-md-12 col-lg-6 my-1">
          <% if assignment.teaching_assistant.id != 1 %>
            <%= link_to "帳票出力", index_output_excel_path(@teaching_assistant = assignment.teaching_assistant), target: :_blank, rel: "noopener noreferrer"  ,class: 'btn btn-secondary w-auto no_return' %>
            <%#= link_to "帳票<br>出力".html_safe, index_output_excel_path(@teaching_assistant = assignment.teaching_assistant), target: :_blank, rel: "noopener noreferrer"  ,class: 'btn btn-secondary w-auto no_return' %>
          <% end %>
        </div>        
      </div>
    </div>
  </div>
<% end %>

app/views/work_hours/create.turbo_stream.erb
<%# 非同期で新規作成時に表示する %>
<%= turbo_stream.prepend "assignments", @work_hour %>
<%= turbo_stream.update "new_work_hour", "" %>

app/views/work_hours/destroy.turbo_stream.erb
<%# Cat詳細（`#cat_1`となる要素）を削除する %>
<%#= turbo_stream.remove @work_hour %>

<%# Flashを表示 %>
<%#= turbo_stream_flash %>

<%= turbo_frame_tag @work_hour %>

<% end %>

app/views/work_hours/edit.html.erb
<%# 非同期の編集時の表示する %>
<%= render "form", work_hour: @work_hour %>

app/views/work_hours/index.html.erb
<%# ===================
===  使用していない  ====
=====================%>
<p style="color: green"><%= notice %></p>

<h1>Work hours</h1>

<div id="work_hours">
  <% @work_hours.each do |work_hour| %>
    <%= render work_hour %>
    <p>
      <%= link_to "Show this work hour", work_hour %>
    </p>
  <% end %>
</div>

<%= link_to "New work hour", new_work_hour_path %>

app/views/work_hours/new.html.erb
<%# 非同期通信で勤務追加時に表示する %>
<%# <h1>New work hour</h1> %>

<%= render "form", work_hour: @work_hour %>

<%# <br> %>

<div>
  <%#= link_to "Back to ", work_hours_path %>
  <%#= link_to "Back to ", course_assignments_path %>
</div>

app/views/work_hours/show.html.erb
<%# ===================
===  使用していない  ====
=====================%>
<div>
<%= "No content" %>
</div>