config/routes.rb
Rails.application.routes.draw do
  get '/top_page', to: 'sessions#index', as: 'top_page'
  resources :users
  resources :assignments
  
  # 帳票出力用の処理URL
  #post '/assignments/output', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/output_csv', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/index_output_excel/:id', to: 'assignments#output_index', as: 'index_output_excel'
  get '/teaching_assistants/index_destroy', to: 'teaching_assistants#index_destroy', as: 'index_destroy_teaching_assistants'
  delete '/teaching_assistants/index_destroy', to: 'teaching_assistants#destroy'
  resources :teaching_assistants do
    collection {post :import}
  end
  
  get '/courses/index_destroy', to: 'courses#index_destroy', as: 'index_destroy_courses'
  delete '/courses/index_destroy', to: 'courses#destroy'
  delete '/courses/:course_id/assignments/:assignment_id/work_hours/:id', to: 'assignments#destroy', as: 'destroy_course_assignments'
  get '/courses/:course_id/assignments/index_destroy', to: 'assignments#index_destroy', as: 'index_destroy_course_assignments'
  delete '/courses/:course_id/assignments/index_destroy', to: 'assignments#TAdestroy'
  resources :courses do
    resources :assignments
    collection {post :import}
  end
  
  #resources :work_hours  
  resources :courses do
    resources :work_hours  
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # セッション管理
  get "/login",  to: "sessions#new"
  post "/login",  to: "sessions#create"
  get "/admin_login",  to: "sessions#admin_new"
  post "/admin_login",  to: "sessions#admin_create"
  delete "/logout",  to: "sessions#destroy"

  get "/sessions/admin_new",  to: "sessions#admin_new"

  # Defines the root path route ("/")
   root "sessions#new"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # login判定
  before_action :login, only: %i[ index show new edit create update destroy index_destroy import]
  before_action :admin_judge, only: %i[ new index_destroy import]

  # GET /courses or /courses.json
  def index
    @q = Course.ransack(params[:q])
    @courses = @q.result(distinct: true)
    @select_years = Course.pluck(:year).uniq
  end

  # GET /courses/1 or /courses/1.json
  def show
    @course = Course.find(params[:id])
    @q = @course.assignments.ransack(params[:q], course_id_eq: @course.id)
    @q.sorts = "work_hours.dtstart ASC" if @q.sorts.empty?
    @assignments = @q.result(distinct: true)
    @sum_actual_working_minutes = @assignments.map { |assignment| assignment.work_hours.sum(:actual_working_minutes) }.sum
  end

  # GET /courses/new
  def new
    @course = Course.new
    @q = Course.ransack(params[:q])
    @courses = @q.result(distinct: true)
    @select_years = Course.pluck(:year).uniq
  end

  # GET /courses/1/edit
  def edit
    # ============#
    # 使用してない =#
    # ============#
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @q = Course.ransack(params[:q])
    @courses = @q.result(distinct: true)
    @select_years = Course.pluck(:year).uniq
    
    respond_to do |format|
      if @course.save
        redirect_to new_course_path, notice: "科目が追加されました", flash: {color: :green}
        @assignment = Assignment.new({course_id:@course.id, teaching_assistant_id:"1", description:"dammy"})#追加行
        @assignment.save
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end

      #@assignment = Assignment.new({course_id:"1", teaching_assistant_id:"0", description:"dammy"})
      #render template: "assignments/index"  
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if params[:course_ids].nil?
      redirect_to index_destroy_courses_path, notice: "削除したい科目を選択してください", flash: {color: :red}
    else
      @courses = Course.where(id: params[:course_ids])
      @courses.destroy_all
      redirect_to index_destroy_courses_path, notice: "科目が削除されました", flash: {color: :green}
    end
  end
  

  def index_destroy
    @q = Course.ransack(params[:q])
    @courses = @q.result(distinct: true)
    @select_years = Course.pluck(:year).uniq
  end

  def import
    @course_import_flag = false
    @course_import_flag = Course.import(params[:file])
    if params[:file].nil?
      redirect_to new_course_url, notice: "登録する科目マスタデータCSVファイルを選択してください", flash: {color: :red}
    else
      if params[:file]&.content_type == "text/csv"|| params[:file].content_type == "application/vnd.ms-excel"
        if @course_import_flag
          redirect_to courses_url, notice: "新規科目マスタデータを追加しました", flash: {color: :green}
        else
          redirect_to new_teaching_assistant_url, notice: "データが追加されませんでした．既にデータが登録済みか，異なるCSVファイルの可能性があります．", flash: {color: :red}
        end
      else
        redirect_to new_teaching_assistant_url, notice: "CSVファイルのみを受け付けます", flash: {color: :red}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:year, :term, :number, :name, :instructor, :time_budget, :description)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<%# ===================
===  使用していない  ====
=====================%>
<div id="<%= dom_id course %>">
  <p>
    <strong>Year:</strong>
    <%= course.year %>
  </p>

  <p>
    <strong>Term:</strong>
    <%= course.term %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= course.number %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Instructor:</strong>
    <%= course.instructor %>
  </p>

  <p>
    <strong>Time budget:</strong>
    <%= course.time_budget %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= course.description %>
  </p>

</div>

app/views/courses/_form.html.erb
<%# 新規マスタデータ追加画面の個別登録のフォームを表示 %>
<%# <div class="row"> %>
  <%= form_with(model: course) do |form| %>
    <% if course.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

        <ul>
          <% course.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="row">
      <div class="col-md-4">
        <div class="row mb-3">
          <div class="col-4"><%= form.label :対象年度, style: "display: block",class: "mt-2"  %></div>
          <div class="col-8"><%= form.number_field :year, class: "form-control" %></div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row mb-3">
          <div class="col-4"><%= form.label :学期, style: "display: block",class: "mt-2" %></div>
          <div class="col-8"><%= form.text_field :term, class: "form-control", maxlength: "64" %></div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row mb-3">
          <div class="col-4"><%= form.label :講義番号, style: "display: block",class: "mt-2" %></div>
          <div class="col-8"><%= form.text_field :number, class: "form-control", maxlength: "6" %></div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row mb-3">
          <div class="col-4"><%= form.label :科目名, style: "display: block",class: "mt-2" %></div>
          <div class="col-8"><%= form.text_field :name, class: "form-control", maxlength: "128" %></div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row mb-3">
          <div class="col-4"><%= form.label :担当教員名, style: "display: block",class: "mt-2" %></div>
          <div class="col-8"><%= form.text_field :instructor, class: "form-control", maxlength: "128" %></div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row mb-3">
          <div class="col-4"><%= form.label :割当可能総時間, style: "display: block",class: "mt-2" %></div>
          <div class="col-8"><%= form.number_field :time_budget, class: "form-control", maxlength: "128" %></div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row mb-3">
          <div class="col-4"><%= form.label :備考, style: "display: block",class: "mt-2" %></div>
          <div class="col-8"><%= form.text_field :description, class: "form-control", maxlength: "128" %></div>
        </div> 
      </div>

      <div class="col-12 text-center mt-5">
        <%= form.submit "登録", class: "ms-5 btn btn-primary px-4" %>
        <%= link_to "クリア", new_course_path, class: "ms-5 btn btn-danger px-4" %>
      </div>
    <% end %>
  </div>

app/views/courses/edit.html.erb
<%# ===================
===  使用していない  ====
=====================%>
<h1>編集</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "削除", remove_courses_path %> |
  <%= link_to "コースに戻る", courses_path %>
</div>

app/views/courses/index.html.erb
<%# 科目一覧画面を表示 %>
<div class="row">
  <div class="col-lg-1 col-md-0"></div>
  <%# 科目一覧画面上部の内容 タイトル 検索 %>
  <div class="col-lg-10 col-md-12">
    <% if flash[:color] == "red" %>
      <div class="red-text"><%= flash[:notice] %></div>
    <% elsif flash[:color] == "green" %>
      <div class="green-text"><%= flash[:notice] %></div>
    <% else %>
      <div><%= flash[:notice] %></div>
    <% end %>

    <%# 科目タイトルとマスタデータ関連 %>
    <div class="row">
      <div class="col-lg-4 col-md-12"><h2>科目一覧</h2></div>
      <div class="col-lg-4 col-md-0"></div>
      <% if session[:admin_flag] == true %>
        <div class="col-lg-2 col-md-12 d-flex align-items-center my-1"><%= link_to "科目マスタデータ追加", new_course_path, class: "btn btn-outline-primary" %></div>
        <div class="col-lg-2 col-md-12 d-flex align-items-center my-1"><%= link_to "科目マスタデータ削除", index_destroy_courses_path, class: "btn btn-outline-danger" %></div>
      <% end %>
    </div>
    
    <%# 検索欄 %>
    <div class="card my-3">
      <div class="card-header">
        検索欄
      </div>
      <div class="card-body">
        <form class="row g-3">
          <%= search_form_for @q, html: {class:"row g-3"} do |f| %>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :year_eq, "対象年度", class: "mt-2" %></div>
                <div class="col-8"><%= f.select :year_eq, @select_years, {prompt:"対象年度を選択"}, class: "form-control" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :term_i_cont, "学期", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :term_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "64" %></div>
              </div>  
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :number_i_cont, "講義番号", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :number_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "6" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :name_i_cont, "科目名", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :name_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :instructor_i_cont, "担当教員", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :instructor_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128"%></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :description_i_cont, "備考", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :description_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-12 text-center mt-5">
              <%= f.submit "検索", class: "ms-5 btn btn-primary px-4"%>
              <%= link_to "クリア", courses_path, class: "ms-5 btn btn-danger px-3" %>
            </div>
          <% end %>
        </form>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>

<%# 科目一覧画面の表部分の作成 %>
<div class="row mb-3">
  <div class="col-lg-1 col-md-0"></div>
  <%# TA一覧表部分 %>
  <div class="col-lg-10 col-md-12">
    <div class="card">
      <div class="card-header">
        科目一覧
      </div>
      <div class="card-body m-3">
        <%# TAのカラムのヘッダー %>
        <div class="row border-bottom border-dark pb-3">
          <div class="col my-auto fw-bolder h5">対象年度</div>
          <div class="col my-auto fw-bolder h5">学期</div>
          <div class="col my-auto fw-bolder h5">講義番号</div>
          <div class="col my-auto fw-bolder h5">科目名</div>
          <div class="col my-auto fw-bolder h5">担当教員</div>
          <div class="col my-auto fw-bolder h5">備考</div>
          <div class="col my-auto fw-bolder h5">割当済時間/割当可能総時間(分)</div>
          <div class="col my-auto fw-bolder h5">操作</div>
        </div>
        <%# TAのレコードデータ %>
        <div id="courses">
          <% @courses.each do |course| %>
            <div class="row border-bottom px-3 py-2">
              <div class="col my-auto"><%= course.year %></div>
              <div class="col my-auto"><%= course.term %></div>
              <div class="col my-auto"><%= course.number %></div>
              <div class="col my-auto"><%= course.name %></div>
              <div class="col my-auto"><%= course.instructor %></div>
              <div class="col my-auto"><%= course.description %></div>
              <div class="col my-auto">
                <% assignments = course.assignments.includes(:work_hours) %>
                <% sum_actual_working_minutes = assignments.map { |assignment| assignment.work_hours.sum(:actual_working_minutes) }.sum %>
                <%= sum_actual_working_minutes %>/<%= course.time_budget %>
              </div>
              <div class="col">
                <div clssa="row">
                  <div class="m-1 col-md-10 col-lg-5 no_return">
                    <%= link_to "編集", course_assignments_path(course), class: "btn btn-primary" %>
                  </div>
                  <div class="m-1 col-md-10 col-lg-5 no_return">
                    <%= link_to "閲覧", course_path(course), class: "btn btn-success" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>

<style>
.no_return {
    white-space: nowrap;
}
</style>

app/views/courses/index_destroy.html.erb
<%# 科目マスタデータ削除画面を表示 %>
<div class="row">
  <div class="col-lg-1 col-md-0"></div>
  <%# 科目マスタデータ削除画面の内容 タイトル 検索 %>
  <div class="col-lg-10 col-md-12">
    <% if flash[:color] == "red" %>
      <div class="red-text"><%= flash[:notice] %></div>
    <% elsif flash[:color] == "green" %>
      <div class="green-text"><%= flash[:notice] %></div>
    <% else %>
      <div><%= flash[:notice] %></div>
    <% end %>

    <div class="row">
      <%# 科目タイトルと戻る %>
      <div class="col-lg-4 col-md-12"><h2>科目マスタデータ削除</h2></div>
      <div class="col-lg-6 col-md-0"></div>
      <div class="col-lg-2 col-md-12 d-flex align-items-center">
        <%= link_to "科目一覧に戻る", courses_path, class: "btn btn-outline-danger py-2" %>
      </div>
    </div>

    <%# 検索欄 %>
    <div class="card my-3">
      <div class="card-header">
        検索欄
      </div>
      <div class="card-body">
        <form class="row g-3">
          <%= search_form_for @q, html: {class:"row g-3"} do |f| %>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :year_eq, "対象年度", class: "mt-2" %></div>
                <div class="col-8"><%= f.select :year_eq, @select_years, {prompt:"対象年度を選択"}, class: "form-control" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :term_i_cont, "学期", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :term_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "64" %></div>
              </div>  
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :number_i_cont, "講義番号", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :number_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "6" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :name_i_cont, "科目名", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :name_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :instructor_i_cont, "担当教員", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :instructor_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128"%></div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%= f.label :description_i_cont, "備考", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :description_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-12 text-center mt-5">
              <%= f.submit "検索", class: "ms-5 btn btn-primary px-4"%>
              <%= link_to "クリア", index_destroy_courses_path, class: "ms-5 btn btn-danger px-3" %>
            </div>
          <% end %>
        </form>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>


<%# 削除選択表 %>
<%= form_tag index_destroy_courses_path, method: :delete, data: {turbo_confirm: "科目に関連する割当がある場合，割当も削除されます．選択した科目を本当に削除しますか？"} do %>
<div class="row mb-3">
  <div class="col-lg-1 col-md-0"></div>
  <%# TA一覧表部分 %>
  <div class="col-lg-10 col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-3 d-flex align-items-center">科目一覧(削除)</div>
          <div class="col-9"><%= submit_tag '選択したものをすべて削除', class: "ms-5 btn btn-danger px-3" %></div>
        </div>
      </div>
      <div class="card-body m-3">
        <%# TAのカラムのヘッダー %>
        <div class="row border-bottom border-dark pb-3">
          <div class="col my-auto fw-bolder h5">削除対象科目</div>
          <div class="col my-auto fw-bolder h5">対象年度</div>
          <div class="col my-auto fw-bolder h5">学期</div>
          <div class="col my-auto fw-bolder h5">講義番号</div>
          <div class="col my-auto fw-bolder h5">科目名</div>
          <div class="col my-auto fw-bolder h5">担当教員</div>
          <div class="col my-auto fw-bolder h5">備考</div>
          <div class="col my-auto fw-bolder h5">割当可能総時間(分)</div>
        </div>
        <%# TAのレコードデータ %>
        <div id="courses">
          <% @courses.each do |course| %>
            <div class="row border-bottom px-3 py-4">
              <div class="col my-auto"><%= check_box_tag 'course_ids[]', course.id %></div>
              <div class="col my-auto"><%= course.year %></div>
              <div class="col my-auto"><%= course.term %></div>
              <div class="col my-auto"><%= course.number %></div>
              <div class="col my-auto"><%= course.name %></div>
              <div class="col my-auto"><%= course.instructor %></div>
              <div class="col my-auto"><%= course.description %></div>
              <div class="col my-auto"><%= course.time_budget %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>
<% end %>

app/views/courses/remove.html.erb
<h1>新規科目マスタデータ削除</h1>

<%= form_tag remove_courses_path, method: :delete do %>
  <%= submit_tag '選択したものをすべて削除' %>

  <table border = "1">
    <tr>
    <th>削除科目選択</th>
    <th>対象年度</th>
    <th>学期</th>
    <th>講義番号</th>
    <th>講義科目名</th>
    <th>担当教員</th>
    <th>TA可能割当総時間(分)</th>
    </tr>
    <div id="courses">
      <% @courses.each do |course| %>
        <tr>
          <td>
            <%= check_box_tag 'course_ids[]', course.id %>
          </td>

          <td>
            <%= course.year %>
          </td>

          <td>
            <%= course.term %>
          </td>

          <td>
            <%= course.number %>
          </td>

          <td>
            <%= course.name %>
          </td>

          <td>
            <%= course.instructor %>
          </td>

          <td>
            <%= course.time_budget %>
          </td>
        </tr>
      <% end %>
    </div>
  </table>
<% end %>

app/views/courses/show.html.erb
<%# TA勤務割当(閲覧)画面 %>
<div class="row">
  <div class="col-lg-1 col-md-0"></div>
  <%# TA勤務割当閲覧上部の内容 %>
  <div class="col-lg-10 col-md-12">
    <%# メッセージ %>
    <% if flash[:color] == "red" %>
      <div class="red-text"><%= flash[:notice] %></div>
    <% elsif flash[:color] == "green" %>
      <div class="green-text"><%= flash[:notice] %></div>
    <% else %>
      <div><%= flash[:notice] %></div>
    <% end %>

    <%# TA勤務割当閲覧 %>
    <div class="row">
      <div class="col-lg-4 col-md-12"><h2>TA勤務割当(閲覧)</h2></div>
      <div class="col-lg-4 col-md-0"></div>
      <div class="col-lg-2 col-md-12 d-flex align-items-center my-1"><%= link_to "TA勤務割当(編集)へ", course_assignments_path(@course), class: "btn btn-outline-success" %></div>
      <div class="col-lg-2 col-md-12 d-flex align-items-center my-1"><%= link_to "科目一覧に戻る", courses_path, class: "btn btn-outline-danger py-2" %></div>
    </div>

    <div class="row m-3">
      <div class="col-3 d-flex align-items-center"><h3 class="">科目：<%= @course.name %></h3></div>
      <div class="col-2 d-flex align-items-center">担当教員: <%= @course.instructor %></div>
      <div class="col-2 d-flex align-items-center">対象年度: <%= @course.year %></div>
      <div class="col-2 d-flex align-items-center">開講学期: <%= @course.term %></div>
      <div class="col-3 d-flex align-items-center">割当可能残時間(分): <%= @course.time_budget - @sum_actual_working_minutes %></div>
    </div>

    <%# 検索欄 %>
    <div class="card my-3">
      <div class="card-header">
        検索欄
      </div>
      <div class="card-body">
        <form class="row g-3">
          <%= search_form_for @q, html: {class:"row g-3"} do |f| %>
            <div class="col-md-4">
              <div class="row">
                <div class="col-4"><%=f.label :teaching_assistant_name_i_cont, "TA名", class: "mt-2" %></div>
                <div class="col-8"><%= f.search_field :teaching_assistant_name_i_cont, placeholder: "条件を入力してください", class: "form-control", maxlength: "128" %></div>
              </div>
            </div>
            <div class="col-12 text-center mt-5">
              <%= f.submit "検索", class: "ms-5 btn btn-primary px-4"%>
              <%= link_to "クリア", course_path(@course), class: "ms-5 btn btn-danger px-4" %>
            </div>
          <% end %>
        </form>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>

<%# TA勤務割当処理 %>
<div class="row mb-3">
  <div class="col-lg-1 col-md-0"></div>
  <div class="col-lg-10 col-md-12">
    <div class="card my-3">
      <div class="card-header">
        <div class="row">
          <div class="col-lg-4 col-md-12 d-flex align-items-center">TA勤務割当処理</div>
          <div></div class="col-lg-8 col-md-0">
        </div>
      </div>
      <div class="card-body mx-3">
        <div class="row border-bottom border-dark pb-3">
          <div class="col my-auto fw-bolder h5">日付</div>
          <div class="col my-auto fw-bolder h5">開始時刻</div>
          <div class="col my-auto fw-bolder h5">終了時刻</div>
          <div class="col my-auto fw-bolder h5">実働時間(分)</div>
          <div class="col my-auto fw-bolder h5">割当TA名</div>
          <div class="col my-auto fw-bolder h5">操作</div>
        </div>
        <div id="assignments">
        <% @assignments.each do |assignment| %>
          <% assignment.work_hours.each do |work_hour| %>
            <div class="row border-bottom px-3 py-2">
              <div class="col my-auto"><%= work_hour.date %></div>
              <div class="col my-auto"><%= work_hour.dtstart.strftime("%H:%M") %></div>
              <div class="col my-auto"><%= work_hour.dtend.strftime("%H:%M") %></div>
              <div class="col my-auto"><%= work_hour.actual_working_minutes %></div>
              <div class="col my-auto">
                <% if assignment.teaching_assistant.id == 1 %>
                  <%= "未登録" %>
                <% else %>
                  <%= assignment.teaching_assistant.name %>
                <% end %>
              </div>
              <div class="col my-auto">
                <% if assignment.teaching_assistant.id != 1 %>
                  <%= link_to "帳票出力", index_output_excel_path(@teaching_assistant = assignment.teaching_assistant), target: :_blank, rel: "noopener noreferrer"  ,class: 'btn btn-secondary' %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-1 col-md-0"></div>
</div>