config/routes.rb
Rails.application.routes.draw do
  get '/top_page', to: 'sessions#index', as: 'top_page'
  resources :users
  resources :assignments
  
  # 帳票出力用の処理URL
  #post '/assignments/output', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/output_csv', to: 'assignments#output', as: 'ta_assignment_output_csv'
  get 'ta_assignment/index_output_excel/:id', to: 'assignments#output_index', as: 'index_output_excel'
  get '/teaching_assistants/index_destroy', to: 'teaching_assistants#index_destroy', as: 'index_destroy_teaching_assistants'
  delete '/teaching_assistants/index_destroy', to: 'teaching_assistants#destroy'
  resources :teaching_assistants do
    collection {post :import}
  end
  
  get '/courses/index_destroy', to: 'courses#index_destroy', as: 'index_destroy_courses'
  delete '/courses/index_destroy', to: 'courses#destroy'
  delete '/courses/:course_id/assignments/:assignment_id/work_hours/:id', to: 'assignments#destroy', as: 'destroy_course_assignments'
  get '/courses/:course_id/assignments/index_destroy', to: 'assignments#index_destroy', as: 'index_destroy_course_assignments'
  delete '/courses/:course_id/assignments/index_destroy', to: 'assignments#TAdestroy'
  resources :courses do
    resources :assignments
    collection {post :import}
  end
  
  #resources :work_hours  
  resources :courses do
    resources :work_hours  
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # セッション管理
  get "/login",  to: "sessions#new"
  post "/login",  to: "sessions#create"
  get "/admin_login",  to: "sessions#admin_new"
  post "/admin_login",  to: "sessions#admin_create"
  delete "/logout",  to: "sessions#destroy"

  get "/sessions/admin_new",  to: "sessions#admin_new"

  # Defines the root path route ("/")
   root "sessions#new"
end

app/views/layouts/_button.html.erb
<div class="<%= class_name %>" href="<%= url %>">
<%= button_name %>
</div>

<style>
.<%= class_name %>{
	text-align:center;
	background-color: <%= bg_color %>;
	padding: 10px 20px;
	color:<%= text_color %>;
	text-decoration: none;
	margin:10px 10px;
	border-radius: 30px;
}

</style>

app/views/layouts/_footer.html.erb
<footer class="p-20 footer mt-auto footer" style="padding:30px 10px;">
<!-- Grid container -->
    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-1 col-md-0 mb-0 mb-md-0">
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-5 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase text-light" style="font-size:3vm; margin-bottom: 20px;">岡大関係サイトへ</h5>
          <ul class="list-unstyled mb-0">
            <li><%= link_to "岡大ホームページ", "https://www.okayama-u.ac.jp/tp/life/syllabus_link.html" ,class: "text-decoration-none ms-4 link-secondary"%></li>
            <li><%= link_to "ソフトウェア開発法ホームページ", "http://sdm.swlab.cs.okayama-u.ac.jp" ,class: "text-decoration-none ms-4 link-secondary"%></li>
          <ul class="list-unstyled mb-0">
            
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-5 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase text-light" style="font-size:3vm; margin-bottom: 20px;">サービス</h5>

          <ul class="list-unstyled mb-0">
            <li><%= link_to "HOME", top_page_path ,class: "text-decoration-none ms-4 link-secondary"%></li>
            <li><%= link_to "TA一覧", teaching_assistants_path ,class: "text-decoration-none ms-4 link-secondary"%></li>
            <li><%= link_to "科目一覧", courses_path ,class: "text-decoration-none ms-4 link-secondary" %></li>
            <% if session[:admin_flag] == true %>
              <li><%= link_to "TAマスタデータ追加", new_teaching_assistant_path ,class: "text-decoration-none ms-4 link-secondary"%></li>
              <li><%= link_to "TAマスタデータ削除", index_destroy_teaching_assistants_path ,class: "text-decoration-none ms-4 link-secondary"%></li>
              <li><%= link_to "科目マスタデータ追加", new_course_path ,class: "text-decoration-none ms-4 link-secondary"%></li>
              <li><%= link_to "科目マスタデータ削除", index_destroy_courses_path ,class: "text-decoration-none ms-4 link-secondary"%></li>
              <li><%= link_to "ユーザ一覧", users_path, method: :get, class: "text-decoration-none ms-4 link-secondary"%></li>
            <% end %>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-1 col-md-0 mb-0 mb-md-0">
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->
</footer>

<style>
  .footer{
    background-color: #212836;
    /* background-color: #dcdcdc; */
  }
</style>

app/views/layouts/_header.html.erb
<%# Header %>
<nav class="navbar sticky-top navbar-expand-sm navbar-light mb-3 z-50 header">
  <div>
    <%= link_to "TA時間管理システム", top_page_path, method: :get, class: "navbar-brand text-white ms-5" %>
  </div>
  <div class="collapse navbar-collapse container-fluid" id="navbarNav">
    <ul class="navbar-nav">
      <li><%= link_to "HOME", top_page_path, method: :get, class: "nav-link text-white ms-2" %></li>
      <li><%= link_to "TA一覧", teaching_assistants_path, method: :get, class: "nav-link text-white ms-2" %></li>
      <li><%= link_to "科目一覧", courses_path, method: :get, class: "nav-link text-white ms-2" %></li>
      <li>
        <% if session[:admin_flag] == true %>
          <li><%= link_to "ユーザ一覧", users_path, method: :get, class: "nav-link text-white ms-2" %></li>
        <% end %>
      </li>
    </ul>

    <%# ログアウト %>
    <details class="row justify-content-end">
    <summary style="list-style: none;" class="login-details me-3 header-summary">
        <div class="d-inline-flex align-items-center">
          <%= image_tag("user.png", alt: "ログアウト", width: 40, height: 40 , class: "img") %>
            <% if session[:admin_flag] == true %>
              <div class="nav-link text-white ms-2">管理者:<%= session[:user_name] %></div>
            <% else%>
              <div class="nav-link text-white ms-2 ">利用者：<%= session[:user_name] %></div>
            <% end %>
          </div>
      </summary>
      <div class=" p-1">
        <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete }, class: "nav-link text-white ms-5" %>
      </div>
    </details>
  </div>
</nav>


<style>
  .header{
    <% if session[:admin_flag] == true %>
      background-color: #000000;
    <% else%>
      background-color: #0071c5;
    <% end %>
  }

  .login_details{

  }
  .header-summary {
  /* ヘッダー部分のsummaryに適用するスタイル */
  ...
  }

</style>

<script>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Takin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script type="module">
      import { Toast } from "bootstrap.esm.min.js";

      Array.from(document.querySelectorAll(".toast")).forEach(
        (toastNode) => new Toast(toastNode)
      );
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body class="d-flex flex-column footerFixed" style="overflow-x: hidden;">
    <% unless current_page?(root_path) or current_page?("/sessions/admin_new") or current_page?(admin_login_path) or current_page?(login_path) %>
      <%= render partial: 'layouts/header' %>
    <% end %>
    <div class="" style="min-height: 537px">
      <%= yield %>
    </div>
    <% unless current_page?(root_path) or current_page?("/sessions/admin_new") or current_page?(admin_login_path) or current_page?(login_path) %>
      <%= render partial: 'layouts/footer' %>
    <% end %>
  </body>
</html>


<style>
  .footerFixed{
    min-height: 100vh; /* ←コンテンツの高さの最小値＝ブラウザの高さに指定 */
  }

</style>